### ISSUE TITLE
TypeError: Error while loading rule 'spellcheck/spell-checker'

### ISSUE THREAD

**Issue by kobymeir** [aotaduy/eslint-plugin-spellcheck#14]
Hi,
I'm getting this error while loading spell checker

TypeError: Error while loading rule 'spellcheck/spell-checker': dictionaryTable[word].push is not a function
the error is from this file at line #241 `dictionaryTable[word].push(rules);`
node_modules/eslint-plugin-spellcheck/node_modules/hunspell-spellchecker/lib/dictionary.js

this is my configuration for eslint:

```
    rules: {
        'spellcheck/spell-checker':
        [
            1,
            {
                comments: 'true',
                strings: 'true',
                identifiers: 'true',
                skipWords: require('../../dictionary.json'),
                skipIfMatch: [
                    'http://[^s]*',
                    'https://[^s]*'
                ]
            }
        ],
      },
    plugins: [
        'spellcheck'
    ]
```

**Comment by aotaduy** [comment]
can you please paste the contents of your dictionary.json ?

**Comment by kobymeir** [comment]
@aotaduy i have tried it also without my dictionary, still fails.


here is the stack trace:

/root/folder/<my_module_name>/node_modules/eslint/lib/eslint.js:819
                    throw ex;
                    ^

TypeError: Error while loading rule 'spellcheck/spell-checker': dictionaryTable[word].push is not a function
    at addWord (/root/folder/<my_module_name>/node_modules/eslint-plugin-spellcheck/node_modules/hunspell-spellchecker/lib/dictionary.js:241:31)
    at Dictionary._parseDIC (/root/folder/<my_module_name>/node_modules/eslint-plugin-spellcheck/node_modules/hunspell-spellchecker/lib/dictionary.js:301:13)
    at Dictionary.parse (/root/folder/<my_module_name>/node_modules/eslint-plugin-spellcheck/node_modules/hunspell-spellchecker/lib/dictionary.js:61:33)
    at Spellchecker.parse (/root/folder/<my_module_name>/node_modules/eslint-plugin-spellcheck/node_modules/hunspell-spellchecker/lib/index.js:18:10)
    at module.exports (/root/folder/<my_module_name>/node_modules/eslint-plugin-spellcheck/rules/spell-checker.js:30:24)
    at /root/folder/<my_module_name>/node_modules/eslint/lib/eslint.js:808:25
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/root/folder/<my_module_name>/node_modules/eslint/lib/eslint.js:780:16)
    at processText (/root/folder/<my_module_name>/node_modules/eslint/lib/cli-engine.js:260:31)
    at CLIEngine.executeOnText (/root/folder/<my_module_name>/node_modules/eslint/lib/cli-engine.js:739:26)
